FROM mcr.microsoft.com/devcontainers/base:ubuntu

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y redis-server \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 6379

CMD ["redis-server", "--appendonly", "yes", "--protected-mode", "no", "--bind", "0.0.0.0", "--port", "6379"]

