#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/no-dockerhub/start-stack.sh [--name <stack-name>] [--env-file <path>] [--rebuild] [--fresh]

Options:
  --name <stack-name>  Stack identifier used for container names/state dir (default: law-eye-local)
  --env-file <path>    Secrets env file (default: <user-state>/law-eye/no-dockerhub/<stack>/secrets.env)
  --rebuild            Rebuild local helper images (redis/postgres+pgvector)
  --fresh              Remove the postgres data volume before start (DANGEROUS: wipes data)
EOF
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

STACK_NAME="${LAW_EYE_STACK_NAME:-law-eye-local}"
ENV_FILE=""
ENV_FILE_EXPLICIT=0
REBUILD_IMAGES=0
FRESH=0
RUNNING=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      STACK_NAME="${2:-}"
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:-}"
      ENV_FILE_EXPLICIT=1
      shift 2
      ;;
    --rebuild)
      REBUILD_IMAGES=1
      shift
      ;;
    --fresh)
      FRESH=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$STACK_NAME" ]]; then
  echo "ERROR: --name must not be empty" >&2
  exit 1
fi

DEFAULT_STATE_HOME="${XDG_STATE_HOME:-${HOME}/.local/state}"
DEFAULT_STATE_DIR="${DEFAULT_STATE_HOME}/law-eye/no-dockerhub/${STACK_NAME}"
LEGACY_STATE_DIR="$ROOT/tmp/no-dockerhub/$STACK_NAME"
STATE_DIR_RAW="${LAW_EYE_NO_DOCKERHUB_STATE_DIR:-$DEFAULT_STATE_DIR}"
if [[ -z "${LAW_EYE_NO_DOCKERHUB_STATE_DIR:-}" && -d "$LEGACY_STATE_DIR" ]]; then
  echo "SECURITY WARNING: legacy state dir exists under repo workspace: $LEGACY_STATE_DIR" >&2
  echo "  - This script will NOT use it anymore (to avoid secret sprawl)." >&2
fi
mkdir -p "$STATE_DIR_RAW"
STATE_DIR="$(cd "$STATE_DIR_RAW" && pwd)"
LOG_DIR="$STATE_DIR/logs"
PID_DIR="$STATE_DIR/pids"
mkdir -p "$LOG_DIR" "$PID_DIR"

if [[ -z "${LAW_EYE_NO_DOCKERHUB_STATE_DIR:-}" && -d "$LEGACY_STATE_DIR" ]]; then
  migrate_legacy_env_file() {
    local src="$1"
    local dst="$2"
    if [[ -f "$src" ]]; then
      echo "INFO: migrating legacy env file: ${src} -> ${dst}" >&2
      mkdir -p "$(dirname "$dst")"
      mv "$src" "$dst" 2>/dev/null || { cp "$src" "$dst" && rm -f "$src"; }
      chmod 600 "$dst" >/dev/null 2>&1 || true
    fi
  }

  if [[ ! -f "$STATE_DIR/secrets.env" ]]; then
    migrate_legacy_env_file "$LEGACY_STATE_DIR/.env" "$STATE_DIR/secrets.env"
    migrate_legacy_env_file "$LEGACY_STATE_DIR/.env.e2e" "$STATE_DIR/secrets.env"
  else
    migrate_legacy_env_file "$LEGACY_STATE_DIR/.env" "$STATE_DIR/legacy.repo.secrets.env"
    migrate_legacy_env_file "$LEGACY_STATE_DIR/.env.e2e" "$STATE_DIR/legacy.repo.secrets.e2e.env"
  fi
fi

cleanup_on_exit() {
  local exit_code=$?
  if [[ "$RUNNING" -eq 1 && "$exit_code" -ne 0 && "${LAW_EYE_KEEP_ON_ERROR:-0}" != "1" ]]; then
    echo "Startup failed (exit=$exit_code). Cleaning up stack: $STACK_NAME" >&2
    bash "$ROOT/scripts/no-dockerhub/stop-stack.sh" --name "$STACK_NAME" >/dev/null 2>&1 || true
  elif [[ "$RUNNING" -eq 1 && "$exit_code" -ne 0 && "${LAW_EYE_KEEP_ON_ERROR:-0}" == "1" ]]; then
    echo "Startup failed (exit=$exit_code). Keeping stack for debugging: $STACK_NAME" >&2
  fi
}
trap cleanup_on_exit EXIT

if [[ -f "$ROOT/.env" ]]; then
  echo "SECURITY WARNING: repo-root .env detected at $ROOT/.env" >&2
  echo "  - Gitignore is not a control. Do NOT store secrets in the repo workspace." >&2
  echo "  - This script will NOT read it; migrate secrets to your user state dir instead." >&2
fi

if [[ -z "$ENV_FILE" ]]; then
  ENV_FILE="$STATE_DIR/secrets.env"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  if [[ "$ENV_FILE_EXPLICIT" -eq 1 ]]; then
    echo "ERROR: missing env file: $ENV_FILE" >&2
    exit 1
  fi

  echo "INFO: secrets env file not found; generating: $ENV_FILE" >&2
  if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: missing required command: python3" >&2
    echo "Hint: Install Python 3 (used to generate local dev secrets)." >&2
    exit 1
  fi
  python3 - "$ENV_FILE" <<'PY'
import os
import secrets
import sys
from pathlib import Path

path = Path(sys.argv[1])
path.parent.mkdir(parents=True, exist_ok=True)

def token() -> str:
    return secrets.token_urlsafe(32)

content = "\n".join(
    [
        "# Auto-generated by scripts/no-dockerhub/start-stack.sh",
        "# DO NOT COMMIT. Keep this file outside the repo workspace.",
        f"POSTGRES_PASSWORD={token()}",
        f"REDIS_PASSWORD={token()}",
        "MINIO_ROOT_USER=minioadmin",
        f"MINIO_ROOT_PASSWORD={token()}",
        "",
    ]
)

path.write_text(content, encoding="utf-8")
PY
  chmod 600 "$ENV_FILE" >/dev/null 2>&1 || true
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: missing env file: $ENV_FILE" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

if [[ -n "${POSTGRES_PASSWORD:-}" ]]; then
  POSTGRES_PASSWORD="$(printf '%s' "$POSTGRES_PASSWORD" | tr -d '\r')"
  export POSTGRES_PASSWORD
fi

if [[ -z "${POSTGRES_PASSWORD:-}" ]]; then
  echo "ERROR: POSTGRES_PASSWORD is empty (env file: $ENV_FILE)" >&2
  exit 1
fi

if [[ -n "${REDIS_PASSWORD:-}" ]]; then
  REDIS_PASSWORD="$(printf '%s' "$REDIS_PASSWORD" | tr -d '\r')"
  export REDIS_PASSWORD
fi

if [[ -z "${REDIS_PASSWORD:-}" ]]; then
  REDIS_PASSWORD="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
)"
  export REDIS_PASSWORD
fi

if [[ -n "${MINIO_ROOT_USER:-}" ]]; then
  MINIO_ROOT_USER="$(printf '%s' "$MINIO_ROOT_USER" | tr -d '\r')"
  export MINIO_ROOT_USER
fi

if [[ -z "${MINIO_ROOT_USER:-}" ]]; then
  MINIO_ROOT_USER="minioadmin"
  export MINIO_ROOT_USER
fi

if [[ -n "${MINIO_ROOT_PASSWORD:-}" ]]; then
  MINIO_ROOT_PASSWORD="$(printf '%s' "$MINIO_ROOT_PASSWORD" | tr -d '\r')"
  export MINIO_ROOT_PASSWORD
fi

if [[ -z "${MINIO_ROOT_PASSWORD:-}" ]]; then
  MINIO_ROOT_PASSWORD="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
)"
  export MINIO_ROOT_PASSWORD
fi

ensure_cmd() {
  local cmd="$1"
  local hint="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: missing required command: $cmd" >&2
    echo "Hint: $hint" >&2
    exit 1
  fi
}

ensure_cmd docker "Install Docker and ensure the daemon is running."
ensure_cmd python3 "Install Python 3 (used for port probing)."
ensure_cmd curl "Install curl (used for readiness checks)."
ensure_cmd pnpm "Install pnpm (used to start apps/web)."

# In non-login shells cargo may not be on PATH. Try sourcing rustup env if present.
if ! command -v cargo >/dev/null 2>&1; then
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck disable=SC1090
    source "$HOME/.cargo/env"
  fi
fi
ensure_cmd cargo "Install Rust toolchain (rustup) and ensure cargo is on PATH."

WEB_RUNS_ON_WINDOWS=0
if [[ "${LAW_EYE_WEB_ON_WINDOWS:-}" == "1" ]]; then
  WEB_RUNS_ON_WINDOWS=1
elif [[ "${LAW_EYE_WEB_ON_WINDOWS:-}" == "0" ]]; then
  WEB_RUNS_ON_WINDOWS=0
else
  # Default: prefer running Web where pnpm is actually usable.
  #
  # On some Windows+WSL setups, pnpm exists on PATH as a WSL script that expects a Linux `node`,
  # but only Windows `node.exe` is installed. In that case, `pnpm` will fail inside WSL with
  # "exec: node: not found", so we must start the Next server on Windows instead.
  if pnpm -v >/dev/null 2>&1; then
    NODE_PLATFORM=""
    if command -v node >/dev/null 2>&1; then
      NODE_PLATFORM="$(node -p "process.platform" 2>/dev/null | tr -d '\r' | tr -d '\n' || true)"
    fi
    if [[ "$NODE_PLATFORM" == "win32" ]]; then
      WEB_RUNS_ON_WINDOWS=1
    else
      WEB_RUNS_ON_WINDOWS=0
    fi
  elif command -v cmd.exe >/dev/null 2>&1 && cmd.exe /c pnpm -v >/dev/null 2>&1; then
    WEB_RUNS_ON_WINDOWS=1
  else
    # Last resort: try detecting the active Node platform (Linux node vs Windows node.exe).
    NODE_PLATFORM=""
    if command -v node >/dev/null 2>&1; then
      NODE_PLATFORM="$(node -p "process.platform" 2>/dev/null | tr -d '\r' | tr -d '\n' || true)"
    elif command -v node.exe >/dev/null 2>&1; then
      NODE_PLATFORM="$(node.exe -p "process.platform" 2>/dev/null | tr -d '\r' | tr -d '\n' || true)"
    fi
    if [[ "$NODE_PLATFORM" == "win32" ]]; then
      WEB_RUNS_ON_WINDOWS=1
    fi
  fi
fi

WEB_MODE="${LAW_EYE_WEB_MODE:-dev}"
if [[ "$WEB_MODE" != "dev" && "$WEB_MODE" != "prod" ]]; then
  echo "ERROR: LAW_EYE_WEB_MODE must be 'dev' or 'prod' (got: $WEB_MODE)" >&2
  exit 1
fi

WEB_ENABLED=1
if [[ "${LAW_EYE_SKIP_WEB:-0}" == "1" ]]; then
  WEB_ENABLED=0
fi

get_primary_ipv4() {
  ip -4 addr show eth0 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1 | head -n 1
}

get_windows_host_ip() {
  local gw=""
  gw="$(ip route 2>/dev/null | awk '/^default / {print $3; exit}' | tr -d '\r' | tr -d '\n' || true)"
  if [[ -n "$gw" ]]; then
    echo "$gw"
    return 0
  fi
  awk '/^nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null | tr -d '\r' | tr -d '\n' || true
}

to_windows_path() {
  local path="$1"

  if command -v wslpath >/dev/null 2>&1; then
    wslpath -w "$path" | tr -d '\r'
    return 0
  fi

  if [[ "$path" =~ ^/mnt/([a-zA-Z])/(.*)$ ]]; then
    local drive="${BASH_REMATCH[1]}"
    local rest="${BASH_REMATCH[2]//\//\\}"
    printf '%s:\\%s' "${drive^^}" "$rest"
    return 0
  fi

  echo "$path"
}

port_free_wsl() {
  local port="$1"
  python3 - "$port" <<'PY'
import socket, sys
port = int(sys.argv[1])
s = socket.socket()
try:
    s.bind(("0.0.0.0", port))
except OSError:
    sys.exit(1)
finally:
    s.close()
sys.exit(0)
PY
}

port_free_windows() {
  local port="$1"

  if command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c "netstat -ano | findstr /R /C\":$port .*LISTENING\" >nul" >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
      return 1
    fi
    return 0
  fi

  if command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -Command "try { if (Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction Stop) { exit 1 } else { exit 0 } } catch { exit 0 }" >/dev/null 2>&1
    return $?
  fi

  return 0
}

port_free() {
  local port="$1"
  port_free_wsl "$port" && port_free_windows "$port"
}

choose_port_wsl() {
  local name="$1"
  shift
  for candidate in "$@"; do
    if port_free_wsl "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done
  echo "ERROR: no free WSL port candidates for $name ($*)" >&2
  return 1
}

choose_port_range_wsl() {
  local name="$1"
  local start="$2"
  local end="$3"

  local candidate
  for ((candidate = start; candidate <= end; candidate++)); do
    if port_free_wsl "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done

  echo "ERROR: no free WSL port in range for $name ($start..$end)" >&2
  return 1
}

choose_port_windows() {
  local name="$1"
  shift
  for candidate in "$@"; do
    if port_free_windows "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done
  echo "ERROR: no free Windows port candidates for $name ($*)" >&2
  return 1
}

choose_port_range_windows() {
  local name="$1"
  local start="$2"
  local end="$3"

  local candidate
  for ((candidate = start; candidate <= end; candidate++)); do
    if port_free_windows "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done

  echo "ERROR: no free Windows port in range for $name ($start..$end)" >&2
  return 1
}

choose_port() {
  local name="$1"
  shift
  for candidate in "$@"; do
    if port_free "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done
  echo "ERROR: no free port candidates for $name ($*)" >&2
  return 1
}

choose_port_range() {
  local name="$1"
  local start="$2"
  local end="$3"

  local candidate
  for ((candidate = start; candidate <= end; candidate++)); do
    if port_free "$candidate"; then
      echo "$candidate"
      return 0
    fi
  done

  echo "ERROR: no free port in range for $name ($start..$end)" >&2
  return 1
}

if [[ -n "${POSTGRES_PORT:-}" ]] && ! port_free_wsl "${POSTGRES_PORT}"; then
  echo "WARN: POSTGRES_PORT=${POSTGRES_PORT} is not available; auto-selecting a free port." >&2
  unset POSTGRES_PORT
fi
if [[ -n "${REDIS_PORT:-}" ]] && ! port_free_wsl "${REDIS_PORT}"; then
  echo "WARN: REDIS_PORT=${REDIS_PORT} is not available; auto-selecting a free port." >&2
  unset REDIS_PORT
fi
if [[ -n "${API_PORT:-}" ]] && ! port_free_wsl "${API_PORT}"; then
  echo "WARN: API_PORT=${API_PORT} is not available; auto-selecting a free port." >&2
  unset API_PORT
fi
if [[ -n "${WEB_PORT:-}" ]]; then
  if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]] && ! port_free_windows "${WEB_PORT}"; then
    echo "WARN: WEB_PORT=${WEB_PORT} is not available on Windows; auto-selecting a free port." >&2
    unset WEB_PORT
  elif [[ "$WEB_RUNS_ON_WINDOWS" -eq 0 ]] && ! port_free_wsl "${WEB_PORT}"; then
    echo "WARN: WEB_PORT=${WEB_PORT} is not available in WSL; auto-selecting a free port." >&2
    unset WEB_PORT
  fi
fi
if [[ -n "${MINIO_API_PORT:-}" ]] && ! port_free_wsl "${MINIO_API_PORT}"; then
  echo "WARN: MINIO_API_PORT=${MINIO_API_PORT} is not available; auto-selecting a free port." >&2
  unset MINIO_API_PORT
fi
if [[ -n "${MINIO_CONSOLE_PORT:-}" ]] && ! port_free_wsl "${MINIO_CONSOLE_PORT}"; then
  echo "WARN: MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT} is not available; auto-selecting a free port." >&2
  unset MINIO_CONSOLE_PORT
fi

POSTGRES_PORT="${POSTGRES_PORT:-$(choose_port_range_wsl postgres 15435 15550 2>/dev/null || choose_port_wsl postgres 5435 5436)}"
REDIS_PORT="${REDIS_PORT:-$(choose_port_range_wsl redis 16380 16450 2>/dev/null || choose_port_wsl redis 6380 6381)}"
API_PORT="${API_PORT:-$(choose_port_range_wsl api 13000 13150 2>/dev/null || choose_port_wsl api 3001 3003 3005)}"
WEB_PORT="${WEB_PORT:-$(
  if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
    choose_port_range_windows web 18849 18950 2>/dev/null || choose_port_windows web 8849 8850 8851
  else
    choose_port_range_wsl web 18849 18950 2>/dev/null || choose_port_wsl web 8849 8850 8851
  fi
)}"
MINIO_API_PORT="${MINIO_API_PORT:-$(choose_port_range_wsl minio-api 19000 19100 2>/dev/null || choose_port_wsl minio-api 9000)}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-$(choose_port_range_wsl minio-console 19101 19200 2>/dev/null || choose_port_wsl minio-console 9001)}"

if ! port_free_wsl "$POSTGRES_PORT"; then
  echo "ERROR: POSTGRES_PORT=$POSTGRES_PORT is not available" >&2
  exit 1
fi
if ! port_free_wsl "$REDIS_PORT"; then
  echo "ERROR: REDIS_PORT=$REDIS_PORT is not available" >&2
  exit 1
fi
if ! port_free_wsl "$API_PORT"; then
  echo "ERROR: API_PORT=$API_PORT is not available" >&2
  exit 1
fi
if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]] && ! port_free_windows "$WEB_PORT"; then
  echo "ERROR: WEB_PORT=$WEB_PORT is not available on Windows" >&2
  exit 1
fi
if [[ "$WEB_RUNS_ON_WINDOWS" -eq 0 ]] && ! port_free_wsl "$WEB_PORT"; then
  echo "ERROR: WEB_PORT=$WEB_PORT is not available in WSL" >&2
  exit 1
fi
if ! port_free_wsl "$MINIO_API_PORT"; then
  echo "ERROR: MINIO_API_PORT=$MINIO_API_PORT is not available" >&2
  exit 1
fi
if ! port_free_wsl "$MINIO_CONSOLE_PORT"; then
  echo "ERROR: MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT is not available" >&2
  exit 1
fi

echo "Stack: $STACK_NAME"
echo "Using ports: postgres=$POSTGRES_PORT redis=$REDIS_PORT minio=$MINIO_API_PORT api=$API_PORT web=$WEB_PORT"

image_exists() {
  docker image inspect "$1" >/dev/null 2>&1
}

build_redis_image() {
  docker build -t lawsaw-redis:local - <<'EOF'
FROM mcr.microsoft.com/devcontainers/base:ubuntu@sha256:3dcb059253b2ebb44de3936620e1cff3dadcd2c1c982d579081ca8128c1eb319
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get install -y redis-server \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /data
USER 1000:1000
EXPOSE 6379
CMD ["sh", "-c", "test -n \"$REDIS_PASSWORD\" || { echo \"REDIS_PASSWORD is required\" >&2; exit 1; }; exec redis-server --appendonly yes --protected-mode yes --bind 0.0.0.0 --port 6379 --requirepass \"$REDIS_PASSWORD\""]
EOF
}

build_postgres_image() {
  docker build -t lawsaw-postgres-pgvector:local - <<'EOF'
FROM mcr.microsoft.com/devcontainers/base:ubuntu@sha256:3dcb059253b2ebb44de3936620e1cff3dadcd2c1c982d579081ca8128c1eb319
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates curl gnupg \
  && rm -rf /var/lib/apt/lists/*

# Install PostgreSQL 16 + pgvector from PGDG.
RUN set -eux; \
  echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt noble-pgdg main" > /etc/apt/sources.list.d/pgdg.list; \
  curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql.gpg; \
  apt-get update; \
  apt-get install -y --no-install-recommends postgresql-16 postgresql-contrib-16 postgresql-16-pgvector; \
  rm -rf /var/lib/apt/lists/*

ENV PGDATA=/var/lib/postgresql/data
RUN mkdir -p /var/lib/postgresql/data \
  && chown -R postgres:postgres /var/lib/postgresql \
  && chmod 700 /var/lib/postgresql/data

RUN cat > /usr/local/bin/docker-entrypoint.sh <<'EOS'
#!/usr/bin/env bash
set -euo pipefail

PGDATA="${PGDATA:-/var/lib/postgresql/data}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
POSTGRES_DB="${POSTGRES_DB:-postgres}"

BIN="/usr/lib/postgresql/16/bin"

if [[ -z "${POSTGRES_PASSWORD}" ]]; then
  echo "ERROR: POSTGRES_PASSWORD is required" >&2
  exit 1
fi
if [[ "${POSTGRES_PASSWORD}" == "postgres" || "${POSTGRES_PASSWORD}" == "password" ]]; then
  echo "ERROR: POSTGRES_PASSWORD must not be a default value" >&2
  exit 1
fi
if [[ -z "${POSTGRES_USER}" ]]; then
  echo "ERROR: POSTGRES_USER is required" >&2
  exit 1
fi
if [[ -z "${POSTGRES_DB}" ]]; then
  echo "ERROR: POSTGRES_DB is required" >&2
  exit 1
fi

if [ ! -s "${PGDATA}/PG_VERSION" ]; then
  mkdir -p "${PGDATA}"
  chmod 700 "${PGDATA}"
  "${BIN}/initdb" -D "${PGDATA}" --encoding=UTF8 --locale=C

  echo "listen_addresses='*'" >> "${PGDATA}/postgresql.conf"
  echo "password_encryption='scram-sha-256'" >> "${PGDATA}/postgresql.conf"
  echo "host all all 0.0.0.0/0 scram-sha-256" >> "${PGDATA}/pg_hba.conf"
  echo "host all all ::/0 scram-sha-256" >> "${PGDATA}/pg_hba.conf"

  "${BIN}/pg_ctl" -D "${PGDATA}" -o "-c listen_addresses='*'" -w start

  psql -v ON_ERROR_STOP=1 --username=postgres -v app_user="${POSTGRES_USER}" -v app_pass="${POSTGRES_PASSWORD}" <<'SQL'
SELECT format(
  'CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS',
  :'app_user',
  :'app_pass'
) WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_user');
\gexec

SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS',
  :'app_user',
  :'app_pass'
) WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_user');
\gexec
SQL

  psql -v ON_ERROR_STOP=1 --username=postgres -v app_user="${POSTGRES_USER}" <<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'law_eye_app') THEN
        CREATE ROLE law_eye_app NOLOGIN NOSUPERUSER NOBYPASSRLS;
    END IF;
END $$;

ALTER ROLE law_eye_app NOLOGIN NOSUPERUSER NOBYPASSRLS;

SELECT format('GRANT law_eye_app TO %I', :'app_user');
\gexec
SQL

  psql -v ON_ERROR_STOP=1 --username=postgres -v db_name="${POSTGRES_DB}" -v db_owner="${POSTGRES_USER}" <<'SQL'
SELECT format('CREATE DATABASE %I OWNER %I', :'db_name', :'db_owner')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'db_name');
\gexec

SELECT format('ALTER DATABASE %I OWNER TO %I', :'db_name', :'db_owner')
WHERE EXISTS (SELECT 1 FROM pg_database WHERE datname = :'db_name');
\gexec
SQL

  psql -v ON_ERROR_STOP=1 --username=postgres --dbname="${POSTGRES_DB}" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
  psql -v ON_ERROR_STOP=1 --username=postgres --dbname="${POSTGRES_DB}" -c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;'
  psql -v ON_ERROR_STOP=1 --username=postgres --dbname="${POSTGRES_DB}" -c 'CREATE EXTENSION IF NOT EXISTS vector;'

  "${BIN}/pg_ctl" -D "${PGDATA}" -m fast -w stop
fi

exec "${BIN}/postgres" -D "${PGDATA}" -c listen_addresses='*'
EOS

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

VOLUME ["/var/lib/postgresql/data"]
EXPOSE 5432
USER postgres
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
EOF
}

build_minio_image() {
  docker build -t lawsaw-minio:local - <<'EOF'
FROM mcr.microsoft.com/devcontainers/base:ubuntu@sha256:3dcb059253b2ebb44de3936620e1cff3dadcd2c1c982d579081ca8128c1eb319
ARG DEBIAN_FRONTEND=noninteractive
ARG MINIO_VERSION=RELEASE.2025-09-07T16-13-09Z
ARG MINIO_SHA256=7c5bd8512c6e966455b1d198209358b2d191c77a83ab377c4073281065fb855f

RUN set -eux; \
  apt-get update; \
  apt-get install -y ca-certificates curl; \
  rm -rf /var/lib/apt/lists/*; \
  test -n "$MINIO_SHA256"; \
  url="https://dl.min.io/server/minio/release/linux-amd64/archive/minio.${MINIO_VERSION}"; \
  curl -fsSL --connect-timeout 20 --max-time 600 --retry 5 --retry-all-errors --retry-delay 3 "$url" -o /usr/local/bin/minio; \
  test -s /usr/local/bin/minio; \
  echo "${MINIO_SHA256}  /usr/local/bin/minio" | sha256sum -c -; \
  chmod +x /usr/local/bin/minio

WORKDIR /data
USER 1000:1000
EXPOSE 9000 9001

ENTRYPOINT ["/usr/local/bin/minio"]
CMD ["server", "/data", "--console-address", ":9001"]
EOF
}

echo "Ensuring local images exist (Docker Hub is unavailable; using MCR base image)..."

if [[ "$REBUILD_IMAGES" -eq 1 ]] || ! image_exists lawsaw-redis:local; then
  echo "Building image: lawsaw-redis:local"
  build_redis_image
else
  echo "Using existing image: lawsaw-redis:local"
fi

if [[ "$REBUILD_IMAGES" -eq 1 ]] || ! image_exists lawsaw-postgres-pgvector:local; then
  echo "Building image: lawsaw-postgres-pgvector:local"
  build_postgres_image
else
  echo "Using existing image: lawsaw-postgres-pgvector:local"
fi

MINIO_IMAGE="lawsaw-minio:local"
if [[ "$REBUILD_IMAGES" -eq 1 ]]; then
  echo "Building image: $MINIO_IMAGE"
  build_minio_image
elif image_exists "$MINIO_IMAGE"; then
  echo "Using existing image: $MINIO_IMAGE"
else
  if image_exists alpine/minio:RELEASE.2025-10-15T17-29-55Z; then
    MINIO_IMAGE="alpine/minio:RELEASE.2025-10-15T17-29-55Z"
    echo "Using existing image: $MINIO_IMAGE"
  else
    echo "Building image: $MINIO_IMAGE"
    build_minio_image
  fi
fi

POSTGRES_CONTAINER="${STACK_NAME}-postgres"
REDIS_CONTAINER="${STACK_NAME}-redis"
MINIO_CONTAINER="${STACK_NAME}-minio"
POSTGRES_VOLUME="${STACK_NAME}-postgres-data"
REDIS_VOLUME="${STACK_NAME}-redis-data"
MINIO_VOLUME="${STACK_NAME}-minio-data"

dump_container_debug() {
  local container="$1"
  local label="$2"
  local ps_file="$LOG_DIR/${label}.ps.txt"
  local inspect_file="$LOG_DIR/${label}.inspect.json"
  local log_file="$LOG_DIR/${label}.docker.log"

  docker ps -a --filter "name=^/${container}$" --format "table {{.Names}}\t{{.Status}}\t{{.Image}}\t{{.Ports}}" >"$ps_file" 2>&1 || true
  docker inspect "$container" >"$inspect_file" 2>&1 || true
  docker logs "$container" >"$log_file" 2>&1 || true
}

echo "Starting containers..."
docker rm -f "$POSTGRES_CONTAINER" >/dev/null 2>&1 || true
docker rm -f "$REDIS_CONTAINER" >/dev/null 2>&1 || true
docker rm -f "$MINIO_CONTAINER" >/dev/null 2>&1 || true

if [[ "$FRESH" -eq 1 ]]; then
  echo "Wiping postgres volume: $POSTGRES_VOLUME"
  docker volume rm -f "$POSTGRES_VOLUME" >/dev/null 2>&1 || true
  echo "Wiping redis volume: $REDIS_VOLUME"
  docker volume rm -f "$REDIS_VOLUME" >/dev/null 2>&1 || true
  echo "Wiping minio volume: $MINIO_VOLUME"
  docker volume rm -f "$MINIO_VOLUME" >/dev/null 2>&1 || true
fi

RUNNING=1
echo "Preparing postgres volume..."
docker volume create "$POSTGRES_VOLUME" >/dev/null 2>&1 || true
if ! docker run --rm --user 0:0 \
  --entrypoint sh \
  --network none \
  --read-only \
  --cap-drop ALL \
  --cap-add CHOWN \
  --cap-add DAC_READ_SEARCH \
  --security-opt no-new-privileges \
  --tmpfs /tmp:rw,noexec,nosuid,nodev \
  -v "$POSTGRES_VOLUME":/var/lib/postgresql/data \
  lawsaw-postgres-pgvector:local \
  -c 'set -eux; chown -R 0:0 /var/lib/postgresql/data; chmod 700 /var/lib/postgresql/data; chown -R postgres:postgres /var/lib/postgresql/data; ls -ld /var/lib/postgresql/data' >"$LOG_DIR/postgres.init.log" 2>&1; then
  echo "ERROR: failed to prepare postgres volume. See: $LOG_DIR/postgres.init.log" >&2
  exit 1
fi

echo "Preparing redis volume..."
docker volume create "$REDIS_VOLUME" >/dev/null 2>&1 || true
if ! docker run --rm --user 0:0 \
  --network none \
  --read-only \
  --cap-drop ALL \
  --cap-add CHOWN \
  --security-opt no-new-privileges \
  --tmpfs /tmp:rw,noexec,nosuid,nodev \
  -v "$REDIS_VOLUME":/data \
  lawsaw-redis:local \
  sh -c 'set -eux; mkdir -p /data/appendonlydir; chown -R 1000:1000 /data; ls -ld /data /data/appendonlydir' >"$LOG_DIR/redis.init.log" 2>&1; then
  echo "ERROR: failed to prepare redis volume. See: $LOG_DIR/redis.init.log" >&2
  exit 1
fi

echo "Preparing minio volume..."
docker volume create "$MINIO_VOLUME" >/dev/null 2>&1 || true
if ! docker run --rm --user 0:0 \
  --network none \
  --read-only \
  --cap-drop ALL \
  --cap-add CHOWN \
  --security-opt no-new-privileges \
  --tmpfs /tmp:rw,noexec,nosuid,nodev \
  -v "$MINIO_VOLUME":/data \
  lawsaw-redis:local \
  sh -c 'set -eux; chown -R 1000:1000 /data; ls -ld /data' >"$LOG_DIR/minio.init.log" 2>&1; then
  echo "ERROR: failed to prepare minio volume. See: $LOG_DIR/minio.init.log" >&2
  exit 1
fi

docker run -d --name "$REDIS_CONTAINER" -p "${REDIS_PORT}:6379" -e REDIS_PASSWORD="$REDIS_PASSWORD" -v "$REDIS_VOLUME":/data lawsaw-redis:local >/dev/null
docker run -d --name "$MINIO_CONTAINER" \
  -p "${MINIO_API_PORT}:9000" \
  -p "${MINIO_CONSOLE_PORT}:9001" \
  --user 1000:1000 \
  -e MINIO_ROOT_USER="$MINIO_ROOT_USER" \
  -e MINIO_ROOT_PASSWORD="$MINIO_ROOT_PASSWORD" \
  -v "$MINIO_VOLUME":/data \
  "$MINIO_IMAGE" server /data --console-address ":9001" >/dev/null
docker run -d --name "$POSTGRES_CONTAINER" \
  -p "${POSTGRES_PORT}:5432" \
  --env-file "$ENV_FILE" \
  -e POSTGRES_USER=law_eye \
  -e POSTGRES_DB=law_eye \
  -v "$POSTGRES_VOLUME":/var/lib/postgresql/data \
  lawsaw-postgres-pgvector:local >/dev/null

echo "Waiting for Redis..."
for _ in $(seq 1 60); do
  if docker exec "$REDIS_CONTAINER" redis-cli -a "$REDIS_PASSWORD" ping >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
if ! docker exec "$REDIS_CONTAINER" redis-cli -a "$REDIS_PASSWORD" ping >/dev/null 2>&1; then
  dump_container_debug "$REDIS_CONTAINER" "redis"
  echo "ERROR: Redis did not become ready. Debug logs: $LOG_DIR/redis.docker.log" >&2
  exit 1
fi

echo "Waiting for Postgres..."
postgres_ready_cmd=(docker exec "$POSTGRES_CONTAINER" pg_isready -q -h 127.0.0.1 -p 5432 -U postgres)
postgres_ready_streak=0
for _ in $(seq 1 180); do
  if "${postgres_ready_cmd[@]}" >/dev/null 2>&1; then
    postgres_ready_streak=$((postgres_ready_streak + 1))
    if [[ "$postgres_ready_streak" -ge 3 ]]; then
      break
    fi
  else
    postgres_ready_streak=0
  fi
  sleep 1
done
if [[ "$postgres_ready_streak" -lt 3 ]] || ! "${postgres_ready_cmd[@]}" >/dev/null 2>&1; then
  dump_container_debug "$POSTGRES_CONTAINER" "postgres"
  echo "ERROR: Postgres did not become ready. Debug logs: $LOG_DIR/postgres.docker.log" >&2
  exit 1
fi

# Backward compatibility for existing volumes initialized before BYPASSRLS was added.
docker exec -i "$POSTGRES_CONTAINER" psql -v ON_ERROR_STOP=1 --username=postgres -v app_user="law_eye" <<'SQL'
SELECT format('ALTER ROLE %I BYPASSRLS', :'app_user')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_user');
\gexec
SQL

echo "Waiting for MinIO..."
for _ in $(seq 1 120); do
  if curl -fsS "http://localhost:${MINIO_API_PORT}/minio/health/ready" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
if ! curl -fsS "http://localhost:${MINIO_API_PORT}/minio/health/ready" >/dev/null 2>&1; then
  dump_container_debug "$MINIO_CONTAINER" "minio"
  echo "ERROR: MinIO did not become ready. Debug logs: $LOG_DIR/minio.docker.log" >&2
  exit 1
fi

urlencode() {
  python3 - "$1" <<'PY'
import sys
import urllib.parse
print(urllib.parse.quote(sys.argv[1], safe=""))
PY
}

DB_PASS_ENC="$(urlencode "$POSTGRES_PASSWORD")"
REDIS_PASS_ENC="$(urlencode "$REDIS_PASSWORD")"
DB_URL="postgres://law_eye:${DB_PASS_ENC}@localhost:${POSTGRES_PORT}/law_eye"
REDIS_URL="redis://:${REDIS_PASS_ENC}@localhost:${REDIS_PORT}"

# Web should call same-origin (/api/v1/*) by default.
# Next rewrites proxy these requests to LAW_EYE_API_PROXY_TARGET.
WSL_HOST_IP="${LAW_EYE_WSL_HOST_IP:-}"
WINDOWS_HOST_IP="${LAW_EYE_WINDOWS_HOST_IP:-}"
LAW_EYE_API_PROXY_TARGET="http://localhost:${API_PORT}"
NEXT_PUBLIC_API_URL="http://localhost:${WEB_PORT}"

if [[ -z "$WINDOWS_HOST_IP" ]]; then
  WINDOWS_HOST_IP="$(get_windows_host_ip)"
fi

export LAW_EYE__DATABASE__URL="$DB_URL"
export LAW_EYE__REDIS__URL="$REDIS_URL"
MINIO_ENDPOINT="http://localhost:${MINIO_API_PORT}"
if [[ -z "${LAW_EYE__OBJECT_STORAGE__ENABLED:-}" ]]; then
  export LAW_EYE__OBJECT_STORAGE__ENABLED="true"
fi
if [[ "${LAW_EYE__OBJECT_STORAGE__ENABLED}" == "true" || "${LAW_EYE__OBJECT_STORAGE__ENABLED}" == "1" ]]; then
  export LAW_EYE__OBJECT_STORAGE__ENDPOINT="${LAW_EYE__OBJECT_STORAGE__ENDPOINT:-$MINIO_ENDPOINT}"
  export LAW_EYE__OBJECT_STORAGE__REGION="${LAW_EYE__OBJECT_STORAGE__REGION:-us-east-1}"
  export LAW_EYE__OBJECT_STORAGE__BUCKET="${LAW_EYE__OBJECT_STORAGE__BUCKET:-law-eye}"
  export LAW_EYE__OBJECT_STORAGE__ACCESS_KEY_ID="${LAW_EYE__OBJECT_STORAGE__ACCESS_KEY_ID:-$MINIO_ROOT_USER}"
  export LAW_EYE__OBJECT_STORAGE__SECRET_ACCESS_KEY="${LAW_EYE__OBJECT_STORAGE__SECRET_ACCESS_KEY:-$MINIO_ROOT_PASSWORD}"
  export LAW_EYE__OBJECT_STORAGE__FORCE_PATH_STYLE="${LAW_EYE__OBJECT_STORAGE__FORCE_PATH_STYLE:-true}"
  # Local MinIO in this stack may not support bucket-level SSE APIs consistently.
  export LAW_EYE__OBJECT_STORAGE__SSE_ENABLED="${LAW_EYE__OBJECT_STORAGE__SSE_ENABLED:-false}"
fi
export LAW_EYE__DATABASE__SESSION_ROLE="law_eye_app"
export LAW_EYE__SERVER__HOST="${LAW_EYE__SERVER__HOST:-0.0.0.0}"
export LAW_EYE__SERVER__PORT="$API_PORT"
allowed_origins=()
append_allowed_origin() {
  local origin="${1:-}"
  [[ -z "$origin" ]] && return 0
  for existing in "${allowed_origins[@]:-}"; do
    if [[ "$existing" == "$origin" ]]; then
      return 0
    fi
  done
  allowed_origins+=("$origin")
}

# Always allow the current web port and the canonical dev port (8849) so
# local restarts with dynamic ports do not accidentally break CSRF checks.
append_allowed_origin "http://localhost:${WEB_PORT}"
append_allowed_origin "http://127.0.0.1:${WEB_PORT}"
append_allowed_origin "http://localhost:8849"
append_allowed_origin "http://127.0.0.1:8849"
if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]] && [[ -n "${WINDOWS_HOST_IP:-}" ]]; then
  append_allowed_origin "http://${WINDOWS_HOST_IP}:${WEB_PORT}"
fi
export LAW_EYE__SERVER__ALLOWED_ORIGINS="$(IFS=,; echo "${allowed_origins[*]}")"
# Optional PDF renderer fallback: reuse a locally running Gotenberg when available.
# This keeps PDF export usable in no-dockerhub mode when browserless is unavailable.
if [[ -z "${LAW_EYE__GOTENBERG__URL:-}" ]]; then
  if curl -fsS "http://127.0.0.1:33012/health" >/dev/null 2>&1; then
    export LAW_EYE__GOTENBERG__URL="http://127.0.0.1:33012"
  fi
fi
# E2E/local runs can trigger repeated auth redirects/logins while validating flows.
# Keep limits configurable, but use generous defaults in this local stack runner.
export LAW_EYE__RATE_LIMIT__LOGIN_MAX_REQUESTS="${LAW_EYE__RATE_LIMIT__LOGIN_MAX_REQUESTS:-200}"
export LAW_EYE__RATE_LIMIT__LOGIN_WINDOW_SECONDS="${LAW_EYE__RATE_LIMIT__LOGIN_WINDOW_SECONDS:-60}"
export LAW_EYE__RATE_LIMIT__REGISTER_MAX_REQUESTS="${LAW_EYE__RATE_LIMIT__REGISTER_MAX_REQUESTS:-50}"
export LAW_EYE__RATE_LIMIT__REGISTER_WINDOW_SECONDS="${LAW_EYE__RATE_LIMIT__REGISTER_WINDOW_SECONDS:-3600}"
export LAW_EYE__SECURITY__ALLOW_INTERNAL_SOURCE_URLS="${LAW_EYE__SECURITY__ALLOW_INTERNAL_SOURCE_URLS:-true}"
# Keep local verification deterministic: disable periodic scheduler by default.
# Manual fetch endpoints still work and can be explicitly enabled via env override.
export LAW_EYE_WORKER_SCHEDULER_ENABLED="${LAW_EYE_WORKER_SCHEDULER_ENABLED:-false}"
export WEB_PORT="$WEB_PORT"

# Avoid Windows-mounted target dir issues by placing build artifacts in the WSL filesystem.
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$HOME/.cache/lawsaw-cargo-target}"
CARGO_BUILD_JOBS="${CARGO_BUILD_JOBS:-1}"
CARGO_PROFILE_DEV_DEBUG="${CARGO_PROFILE_DEV_DEBUG:-0}"
LAW_EYE_SKIP_BUILD="${LAW_EYE_SKIP_BUILD:-0}"
mkdir -p "$CARGO_TARGET_DIR"

start_bg() {
  local name="$1"
  local workdir="$2"
  local pid_file="$PID_DIR/$name.pid"
  local log_file="$LOG_DIR/$name.log"
  shift 2

  if [[ -f "$pid_file" ]]; then
    local existing_pid
    existing_pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [[ -n "$existing_pid" ]] && pid_exists "$existing_pid"; then
      # API can be alive with a stale pid file but bound to a different port
      # from a previous stack run. Treat that as stale and restart it.
      if [[ "$name" == "api" ]]; then
        local existing_pid_raw="${existing_pid#wsl:}"
        local listening_pid
        listening_pid="$(wsl_listen_pid "$API_PORT")"
        if [[ -n "$listening_pid" && "$listening_pid" == "$existing_pid_raw" ]]; then
          echo "Process already running: $name (pid=$existing_pid)"
          return 0
        fi
        echo "WARN: stale api pid file detected (pid=$existing_pid, api_port=$API_PORT, listening_pid=${listening_pid:-none}); restarting api." >&2
        rm -f "$pid_file"
      else
        echo "Process already running: $name (pid=$existing_pid)"
        return 0
      fi
    fi
  fi

  echo "Starting $name..."
  (
    cd "$workdir"
    nohup "$@" >"$log_file" 2>&1 &
    echo "wsl:$!" >"$pid_file"
  )
}

pid_exists() {
  local pid="$1"
  pid="$(echo "$pid" | tr -d '\r' | tr -d '\n')"
  if [[ -z "$pid" ]]; then
    return 1
  fi

  if [[ "$pid" == wsl:* ]]; then
    kill -0 "${pid#wsl:}" >/dev/null 2>&1
    return $?
  fi

  if [[ "$pid" == win:* ]]; then
    local win_pid="${pid#win:}"
    if [[ -z "$win_pid" ]]; then
      return 1
    fi
    if command -v tasklist.exe >/dev/null 2>&1; then
      tasklist.exe /FI "PID eq $win_pid" 2>/dev/null | tr -d '\r' | grep -q " $win_pid " && return 0
    fi
    return 1
  fi

  # Safety default: treat unknown format as WSL PID.
  kill -0 "$pid" >/dev/null 2>&1
}

wsl_listen_pid() {
  local port="$1"
  ss -ltnp 2>/dev/null \
    | awk -v p=":${port}" '$4 ~ p { print }' \
    | sed -n 's/.*pid=\([0-9]\+\).*/\1/p' \
    | head -n 1
}

windows_listen_pid() {
  local port="$1"
  if ! command -v powershell.exe >/dev/null 2>&1; then
    return 1
  fi
  powershell.exe -NoProfile -Command "Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty OwningProcess" 2>/dev/null | tr -d '\r' | tr -d '\n' || true
}

start_web_windows() {
  local name="web"
  local pid_file="$PID_DIR/$name.pid"
  local log_file="$LOG_DIR/$name.log"
  local err_file="$LOG_DIR/$name.err.log"

  if [[ -f "$pid_file" ]]; then
    local existing_pid
    existing_pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [[ -n "$existing_pid" ]] && pid_exists "$existing_pid"; then
      local existing_pid_raw="${existing_pid#win:}"
      local listening_pid
      listening_pid="$(windows_listen_pid "$WEB_PORT")"

      if [[ -n "$listening_pid" && "$listening_pid" == "$existing_pid_raw" ]]; then
        echo "Process already running: $name (pid=$existing_pid)"
        return 0
      fi

      echo "WARN: stale web pid file detected (pid=$existing_pid, web_port=$WEB_PORT, listening_pid=${listening_pid:-none}); restarting web." >&2
      rm -f "$pid_file"
    fi
  fi

  ensure_cmd cmd.exe "WSL must have Windows interop enabled (cmd.exe available)."
  ensure_cmd powershell.exe "WSL must have Windows interop enabled (powershell.exe available)."

  local web_workdir_win
  web_workdir_win="$(to_windows_path "$ROOT/apps/web")"
  local log_file_win
  log_file_win="$(to_windows_path "$log_file")"
  local err_file_win
  err_file_win="$(to_windows_path "$err_file")"
  local cmd_file
  cmd_file="$STATE_DIR/web-${WEB_MODE}.cmd"
  local cmd_file_win
  cmd_file_win="$(to_windows_path "$cmd_file")"

  python3 - "$cmd_file" "$web_workdir_win" "$WEB_PORT" "$NEXT_PUBLIC_API_URL" "$LAW_EYE_API_PROXY_TARGET" "$log_file_win" "$err_file_win" "$WEB_MODE" <<'PY'
import pathlib
import sys

path, workdir, web_port, web_origin, proxy_target, out_log, err_log, web_mode = sys.argv[1:]

web_cmd = "pnpm dev"
extra_lines = []
if web_mode == "prod":
    web_cmd = r"node .\\node_modules\\next\\dist\\bin\\next start -p %WEB_PORT% -H %WEB_HOST%"
    extra_lines.append("set NODE_ENV=production")
    # Windows prod builds must NOT force WASM bindings; it breaks `next build` on win32.
    extra_lines.append("set NEXT_TEST_WASM=")
    extra_lines.append(f"call pnpm build 1>> \"{out_log}\" 2>> \"{err_log}\"")

extra_block = "\n".join(extra_lines)
content = f"""@echo off
setlocal
cd /d {workdir}
set WEB_HOST=0.0.0.0
set WEB_PORT={web_port}
set PORT={web_port}
set NEXT_PUBLIC_API_URL={web_origin}
set LAW_EYE_API_PROXY_TARGET={proxy_target}
set NEXT_TELEMETRY_DISABLED=1
{extra_block}
call {web_cmd} 1>> "{out_log}" 2>> "{err_log}"
"""

content = content.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r\n")
pathlib.Path(path).write_text(content, encoding="utf-8", newline="")
PY

  echo "Starting $name..."
  powershell.exe -NoProfile -Command "Start-Process -WindowStyle Hidden -FilePath cmd.exe -WorkingDirectory '${web_workdir_win}' -ArgumentList '/v:on','/c','call \"${cmd_file_win}\"'" >/dev/null 2>&1 || true

  local pid=""
  for _ in $(seq 1 60); do
    pid="$(windows_listen_pid "$WEB_PORT")"
    if [[ -n "$pid" ]]; then
      break
    fi
    sleep 0.5
  done

  if [[ -n "$pid" ]]; then
    echo "win:$pid" >"$pid_file"
  else
    echo "WARN: failed to detect Windows PID for web port $WEB_PORT; stop may require manual cleanup." >&2
  fi
}

API_BIN="$CARGO_TARGET_DIR/debug/law-eye-api"
WORKER_BIN="$CARGO_TARGET_DIR/debug/law-eye-worker"

build_api_and_worker() {
  local jobs="$1"
  local redirect_mode="$2"
  local log_file="$LOG_DIR/cargo-build.log"

  local redir=">"
  if [[ "$redirect_mode" == "append" ]]; then
    redir=">>"
  fi

  if [[ "$redir" == ">>" ]]; then
    (
      cd "$ROOT" && CARGO_PROFILE_DEV_DEBUG="$CARGO_PROFILE_DEV_DEBUG" cargo build -j "$jobs" -p law-eye-api -p law-eye-worker
    ) >>"$log_file" 2>&1
  else
    (
      cd "$ROOT" && CARGO_PROFILE_DEV_DEBUG="$CARGO_PROFILE_DEV_DEBUG" cargo build -j "$jobs" -p law-eye-api -p law-eye-worker
    ) >"$log_file" 2>&1
  fi
}

if [[ "$LAW_EYE_SKIP_BUILD" == "1" ]]; then
  echo "Skipping API + worker build (LAW_EYE_SKIP_BUILD=1)..."
  if [[ ! -f "$API_BIN" || ! -f "$WORKER_BIN" ]]; then
    echo "ERROR: LAW_EYE_SKIP_BUILD=1 but binaries are missing:" >&2
    echo "  - $API_BIN" >&2
    echo "  - $WORKER_BIN" >&2
    exit 1
  fi
else
  echo "Building API + worker (CARGO_TARGET_DIR=$CARGO_TARGET_DIR, CARGO_BUILD_JOBS=$CARGO_BUILD_JOBS)..."
  if ! build_api_and_worker "$CARGO_BUILD_JOBS" "truncate"; then
    if [[ "$CARGO_BUILD_JOBS" != "1" ]]; then
      echo "WARN: cargo build failed with CARGO_BUILD_JOBS=$CARGO_BUILD_JOBS; retrying with CARGO_BUILD_JOBS=1..." >&2
      echo "" >>"$LOG_DIR/cargo-build.log"
      echo "[retry] cargo build -j 1 -p law-eye-api -p law-eye-worker" >>"$LOG_DIR/cargo-build.log"
      if ! build_api_and_worker "1" "append"; then
        echo "ERROR: cargo build failed even after retry with CARGO_BUILD_JOBS=1. See: $LOG_DIR/cargo-build.log" >&2
        exit 1
      fi
    else
      echo "ERROR: cargo build failed with CARGO_BUILD_JOBS=1. See: $LOG_DIR/cargo-build.log" >&2
      exit 1
    fi
  fi
fi

start_bg api "$ROOT" "$API_BIN"

wait_for_api_health() {
  local attempts="${1:-90}"
  for _ in $(seq 1 "$attempts"); do
    if curl -fsS "http://localhost:${API_PORT}/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  curl -fsS "http://localhost:${API_PORT}/health" >/dev/null 2>&1
}

echo "Waiting for API /health..."
api_fix_attempts=0
while ! wait_for_api_health 90; do
  # Compatibility shim for old embedded migrations:
  # migration 034 may reference columns that do not exist in this schema path.
  if [[ "$api_fix_attempts" -lt 2 ]] \
    && grep -q "migration 34" "$LOG_DIR/api.log" 2>/dev/null; then
    api_fix_attempts=$((api_fix_attempts + 1))
    echo "INFO: applying DB compatibility fix for migration 34 (attempt=${api_fix_attempts})..." >&2
    docker exec -i "$POSTGRES_CONTAINER" psql -v ON_ERROR_STOP=1 --username=postgres --dbname=law_eye <<'SQL' >/dev/null
DO $$
BEGIN
    IF to_regclass('public.sources') IS NOT NULL THEN
        ALTER TABLE public.sources ADD COLUMN IF NOT EXISTS next_crawl_at TIMESTAMPTZ;
    END IF;

    IF to_regclass('public.users') IS NOT NULL THEN
        ALTER TABLE public.users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
    END IF;

    IF to_regclass('public.api_keys') IS NOT NULL THEN
        ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
    END IF;

    IF to_regclass('public.webhook_endpoints') IS NOT NULL THEN
        ALTER TABLE public.webhook_endpoints ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
    END IF;

    IF to_regclass('public.feedbacks') IS NOT NULL THEN
        ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS article_id UUID;
    END IF;
END $$;
SQL

    # API exits on migration failure; start it again after applying the shim.
    start_bg api "$ROOT" "$API_BIN"
    continue
  fi

  # Compatibility shim for migration 044:
  # older schema stores role permissions in roles.permissions JSONB (no role_permissions table).
  if [[ "$api_fix_attempts" -lt 3 ]] \
    && grep -q "migration 44" "$LOG_DIR/api.log" 2>/dev/null \
    && grep -q "role_permissions" "$LOG_DIR/api.log" 2>/dev/null; then
    api_fix_attempts=$((api_fix_attempts + 1))
    echo "INFO: applying DB compatibility fix for migration 44 (attempt=${api_fix_attempts})..." >&2
    docker exec -i "$POSTGRES_CONTAINER" psql -v ON_ERROR_STOP=1 --username=postgres --dbname=law_eye <<'SQL' >/dev/null
CREATE TABLE IF NOT EXISTS public.role_permissions (
    role TEXT NOT NULL,
    permission TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (role, permission)
);
ALTER TABLE public.role_permissions OWNER TO law_eye;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.role_permissions TO law_eye;
GRANT SELECT ON public.role_permissions TO law_eye_app;

INSERT INTO public.role_permissions (role, permission)
SELECT r.name, perms.permission
FROM public.roles r
CROSS JOIN LATERAL jsonb_array_elements_text(r.permissions) AS perms(permission)
ON CONFLICT (role, permission) DO NOTHING;
SQL

    start_bg api "$ROOT" "$API_BIN"
    continue
  fi

  if [[ "$api_fix_attempts" -gt 0 ]]; then
    echo "ERROR: API did not become ready after compatibility fixes. See: $LOG_DIR/api.log" >&2
  else
    echo "ERROR: API did not become ready. See: $LOG_DIR/api.log" >&2
  fi
  exit 1
done

start_bg worker "$ROOT" "$WORKER_BIN"

if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]] && [[ "${LAW_EYE_ALLOW_WSL_IP_PROXY:-0}" == "1" ]]; then
  if ! powershell.exe -NoProfile -Command "try { (Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 http://127.0.0.1:${API_PORT}/health).StatusCode } catch { exit 1 }" >/dev/null 2>&1; then
    if [[ -z "$WSL_HOST_IP" ]]; then
      WSL_HOST_IP="$(get_primary_ipv4)"
    fi
    if [[ -z "$WSL_HOST_IP" ]]; then
      echo "ERROR: Windows cannot reach API via localhost and failed to detect WSL IPv4. Set LAW_EYE_WSL_HOST_IP manually." >&2
      exit 1
    fi
    LAW_EYE_API_PROXY_TARGET="http://${WSL_HOST_IP}:${API_PORT}"
    echo "INFO: Windows cannot reach API via localhost. Using LAW_EYE_API_PROXY_TARGET=$LAW_EYE_API_PROXY_TARGET for Next rewrites." >&2
  fi
fi

export NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL"
export LAW_EYE_API_PROXY_TARGET="$LAW_EYE_API_PROXY_TARGET"
if [[ "$WEB_ENABLED" -eq 1 ]]; then
  if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
    start_web_windows
  else
    if [[ "$WEB_MODE" == "prod" ]]; then
      echo "Building Web (prod)..."
      rm -f "$ROOT/apps/web/.next/lock"
      (cd "$ROOT/apps/web" && env NODE_ENV=production pnpm build >"$LOG_DIR/web.build.log" 2>&1)
      start_bg web "$ROOT/apps/web" env NODE_ENV=production node ./node_modules/next/dist/bin/next start -p "$WEB_PORT" -H 0.0.0.0
    else
      start_bg web "$ROOT/apps/web" env WEB_PORT="$WEB_PORT" PORT="$WEB_PORT" pnpm dev
    fi
  fi

  echo "Waiting for Web /login..."
  WEB_READY_WAIT_SECONDS=90
  if [[ "$WEB_MODE" == "prod" ]]; then
    WEB_READY_WAIT_SECONDS=240
  fi
  if [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
    web_ready_windows() {
      if powershell.exe -NoProfile -Command "try { (Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 http://127.0.0.1:${WEB_PORT}/login).StatusCode } catch { exit 1 }" >/dev/null 2>&1; then
        return 0
      fi
      if [[ -n "${WINDOWS_HOST_IP:-}" ]] && curl -fsS "http://${WINDOWS_HOST_IP}:${WEB_PORT}/login" >/dev/null 2>&1; then
        return 0
      fi
      return 1
    }

    for _ in $(seq 1 "$WEB_READY_WAIT_SECONDS"); do
      if web_ready_windows; then
        break
      fi
      sleep 1
    done
    if ! web_ready_windows; then
      echo "ERROR: Web did not become ready. See: $LOG_DIR/web.log ($LOG_DIR/web.err.log)" >&2
      exit 1
    fi

    if [[ ! -f "$PID_DIR/web.pid" ]]; then
      win_pid="$(windows_listen_pid "$WEB_PORT")"
      if [[ -n "$win_pid" ]]; then
        echo "win:$win_pid" >"$PID_DIR/web.pid"
      fi
    fi
  else
    for _ in $(seq 1 "$WEB_READY_WAIT_SECONDS"); do
      if curl -fsS "http://localhost:${WEB_PORT}/login" >/dev/null 2>&1; then
        break
      fi
      sleep 1
    done
    if ! curl -fsS "http://localhost:${WEB_PORT}/login" >/dev/null 2>&1; then
      echo "ERROR: Web did not become ready. See: $LOG_DIR/web.log" >&2
      exit 1
    fi
  fi
else
  echo "Skipping web startup because LAW_EYE_SKIP_WEB=1"
fi

cat >"$STATE_DIR/stack.env" <<EOF
STACK_NAME=$STACK_NAME
POSTGRES_PORT=$POSTGRES_PORT
REDIS_PORT=$REDIS_PORT
MINIO_API_PORT=$MINIO_API_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
MINIO_ENDPOINT=$MINIO_ENDPOINT
API_PORT=$API_PORT
WEB_PORT=$WEB_PORT
NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
LAW_EYE_API_PROXY_TARGET=$LAW_EYE_API_PROXY_TARGET
WEB_RUNS_ON_WINDOWS=$WEB_RUNS_ON_WINDOWS
WEB_ENABLED=$WEB_ENABLED
WSL_HOST_IP=${WSL_HOST_IP:-}
WINDOWS_HOST_IP=${WINDOWS_HOST_IP:-}
EOF

echo "Stack ready:"
echo "  Postgres: localhost:${POSTGRES_PORT}"
echo "  Redis:    localhost:${REDIS_PORT}"
echo "  MinIO:    http://localhost:${MINIO_API_PORT} (console :${MINIO_CONSOLE_PORT})"
echo "  API:      http://localhost:${API_PORT}"
if [[ "$WEB_ENABLED" -eq 1 ]]; then
  echo "  Web:      http://localhost:${WEB_PORT}"
elif [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
  echo "  Web:      skipped (LAW_EYE_SKIP_WEB=1)"
else
  echo "  Web:      skipped (LAW_EYE_SKIP_WEB=1)"
fi
if [[ "$WEB_ENABLED" -eq 1 ]] && [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
  echo "  Web (WSL access): http://${WINDOWS_HOST_IP:-<unknown>}:${WEB_PORT}"
fi
echo "State: $STATE_DIR"

RUNNING=0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               I_PORT}"
echo "  Worker:   http://localhost:${WORKER_HEALTH_PORT}"
if [[ "$WEB_ENABLED" -eq 1 ]]; then
  echo "  Web:      http://localhost:${WEB_PORT}"
elif [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
  echo "  Web:      skipped (LAW_EYE_SKIP_WEB=1)"
else
  echo "  Web:      skipped (LAW_EYE_SKIP_WEB=1)"
fi
if [[ "$WEB_ENABLED" -eq 1 ]] && [[ "$WEB_RUNS_ON_WINDOWS" -eq 1 ]]; then
  echo "  Web (WSL access): http://${WINDOWS_HOST_IP:-<unknown>}:${WEB_PORT}"
fi
echo "State: $STATE_DIR"

RUNNING=0
